### ISSUE TITLE
Tissue should function as a test, failing when the code is not pep8 compliant.

### ISSUE THREAD

**Issue by wolph** [wolph/tissue#10]
Showing these is nice but I want to force pep8 compliance for passing the tests, that way people will always adhere to pep8 (otherwise travis won't accept the commit).

**Comment by mlopes** [comment]
Hi, 

Is this project still being maintained? Would it be worth it to make a pull request with a fix for this, or would it be better to just fork into a new project?

Cheers

**Comment by jkoelker** [comment]
@mlopes I haven't had time to hack on this in quite a while, I'd accept pull requests and make releases, or if you'd rather take ownership, I can transfer it in pypi to your account.

Happy Hacking!

**Comment by mlopes** [comment]
Hi, 

Thanks for your answer, right now I'm only interested in fixing this issue, so I guess I'll just work on making a pull request.

Cheers

**Comment by wolph** [comment]
I would be willing to maintain the project as I'm still using nose and tissue for quite a few of my other projects. But I have to say that I have switched to py.test for my new projects since it debugs quite a bit easier.

**Comment by jkoelker** [comment]
@WoLpH Thanks, if your pypi username is the same, then you should have Owner access to it. If its not the same, let me know.  If all is bueno, then I'll transfer the repo over as well. +1 on py.test. I've also been using tox more and do style checking as a separate job there.

**Comment by wolph** [comment]
Yep, transferred succesfully :)

Thanks, I'll take a look at the open issues soon.

**Comment by mlopes** [comment]
Should I still give it a go at trying to add this feature or are you picking it up? I was thinking of finding out how to tell nose to exit with a non 0 exit code, and do it based on a command line option, to prevent regression issues.

Cheers

**Comment by wolph** [comment]
If you have the time for it, please do. I won't have time within a week at least

**Comment by mlopes** [comment]
Ok, so I gave it a try today, without much success. The problem seems to be, because the pep8 validation is not running as a test, I haven't been able to cause nose to exit with nonzero status. I tried raising an AssertionException and creating an empty nose.case.Test and adding a addFailure method. None of those had the desired result.

I might be missing something very obvious here, since this is the first time I look into the nose plugin interface.

**Comment by wolph** [comment]
I believe you could use the `cover` plugin as an example: https://github.com/nose-devs/nose/blob/master/nose/plugins/cover.py#L195

It has a `cover-min-percentage` parameter which basically does the same as tissue does.

**Comment by wolph** [comment]
Fixed in 93a38ceb2b6d7ea68802650dc1e2a5696c5b6b32

**Comment by mlopes** [comment]
Was trying to avoid halting the executions of all the other tests. But guess this is the only way to do it from outside a test.

**Comment by wolph** [comment]
Not sure if it's the only way, but since Nose uses this for the internal plugins, I would assume it's "the way"

**Comment by mlopes** [comment]
My point here is that nose has an option to stop on first failure, or continue with the remaining tests. By using sys.exit the program halts and nothing else will run. I guess the reason why even the internal plugins do it is because the plugin interface wasn't thought to have something that is not a test causing a nonzero exit.

Thanks for taking the time to fix this, it's now possible to use tissue in a CI environment to check the build status.

**Comment by wolph** [comment]
Yes, I see your point.

Unfortunately, looking at the plugin interface (https://nose.readthedocs.org/en/latest/plugins/interface.html) the only other option I can think of is dynamically adding tests which execute pep8 on the files. Not sure if that's the cleaner option in total but it's definitely a lot more work.

**Comment by mlopes** [comment]
Yeah, that sounds like some major refactoring and brings a lot of questions about at which level would the test be created (per file, per package, one test for the whole process). It seems like the cleaner option, but pragmatically, adding the sys.exit was a better call, as it resolved the issue in a very short amount of time.

Cheers,
Marco Lopes
